name: Build Installer
on: 
  push:
    branches:
      - windows
env:
  APPNAME
  APPVERSION
jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: /O+
      
      - uses: actions/upload-artifact@v4
        with:
          path: D:\a\VA-11-Hall-A-French-Translation\VA-11-Hall-A-French-Translation\Output\*