name: Build RC Artifacts
on: workflow_dispatch

jobs:
  build:
    name: Setup and Tarball build
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Git LFS Pull 
        run: git lfs pull

      - name: Setting env vars from .env
        uses: xom9ikk/dotenv@v2.3.0

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"

      - name: Compile Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        env:
          APPNAME: ${{ env.APPNAME }}
          APPVERSION: ${{ env.APPVERSION }}_RCBuild-${{ steps.date.outputs.date }}
        with:
          path: setup.iss
          options: /O+

      - name: Compile PS-Edition Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        env:
          APPNAME: ${{ env.APPNAME }}
          APPVERSION: ${{ env.APPVERSION }}_RCBuild-${{ steps.date.outputs.date }}
        with:
          path: setup_ps-edition.iss
          options: /O+
      
      - name: Prepare Windows std files
        shell: bash
        run: |
          mkdir win
          cp -r scripts win/scripts
          mv data.win win/data.win
          ls -laR win

      - name: Prepare Windows PS files
        shell: bash
        run: |
          mkdir win-ps
          cp -r scripts win-ps/scripts
          cp ps/data.win win-ps/data.win
          ls -laR win-ps
      
      - name: Compress Windows Manual Version
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 win.7z ./win/

      - name: Compress Windows Manual Version PS
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 win-ps.7z ./win-ps/

      - name: Move Windows manual versions to Outputs
        shell: bash
        run: |
          mkdir Output
          mv win.7z Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer.7z
          mv win-ps.7z Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition.7z

      - name: Prepare Linux std files
        shell: bash
        run: |
          mkdir assets
          mv scripts assets/scripts
          mv data.win assets/game.unx
          ls -laR assets

      - name: Compress Linux std files
        uses: a7ul/tar-action@v1.2.0
        id: compress2
        with:
          command: c
          cwd: ./
          files: |
            ./assets/
            ./Lisez-Moi-PatchFR_Linux.txt
          outPath: Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Linux.tar.gz

      - name: Prepare Linux PS files
        shell: bash
        run: |
          rm assets/game.unx
          mv ps/data.win assets/game.unx
          ls -laR assets

      - name: Compress Linux ps files
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./assets/
            ./Lisez-Moi-PatchFR_Linux.txt
          outPath: Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Linux_PS-Edition.tar.gz
      
      - name: Prepare Vita std files
        shell: bash
        run: |
          mkdir -p Vita/rePatch/PCSB01166/games/
          cp -r scripts Vita/rePatch/PCSB01166/games/scripts
          cp Vita/rePatch/PCSB01166/games/scripts/eng Vita/rePatch/PCSB01166/games/scripts/en
          cp vita/game.win Vita/rePatch/PCSB01166/games/game.win
          ls -laR assets

      - name: Prepare Vita PS files
        shell: bash
        run: |
          mkdir -p Vita-PS/rePatch/PCSB01166/games/
          cp -r scripts Vita-PS/rePatch/PCSB01166/games/scripts
          cp Vita-PS/rePatch/PCSB01166/games/scripts/eng Vita-PS/rePatch/PCSB01166/games/scripts/en
          cp vita/ps/game.win Vita/rePatch/PCSB01166/games/game.win
          ls -laR assets
      
      - name: Compress Vita Version
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 Vita.7z ./Vita/

      - name: Compress Vita Version PS
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 Vita-PS.7z ./Vita-PS/

      - name: Move Windows manual versions to Outputs
        shell: bash
        run: |
          mkdir Output
          mv Vita.7z Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Vita.7z 
          mv Vita-PS.7z Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Vita_PS-Edition.7z 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: D:\a\VA-11-Hall-A-French-Translation\VA-11-Hall-A-French-Translation\Output\*
