name: Build Installer
on: 
  push:
    branches:
      - windows

jobs:
  build:
    name: Setup and Tarball build
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Git LFS Pull 
        run: git lfs pull
        
      - name: Setting env vars from .env
        uses: xom9ikk/dotenv@v2.3.0

      - name: Compile Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        env:
          APPNAME: ${{ env.APPNAME }}
          APPVERSION: ${{ env.APPVERSION }}
        with:
          path: setup.iss
          options: /O+

      - name: Compile PS-Edition Windows Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        env:
          APPNAME: ${{ env.APPNAME }}
          APPVERSION: ${{ env.APPVERSION }}
        with:
          path: setup_ps-edition.iss
          options: /O+
      
      - name: Prepare Windows std files
        shell: bash
        run: |
          mkdir ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer
          cp -r scripts ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer/scripts
          cp data.win ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer/data.win
          ls -laR ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer

      - name: Prepare Windows PS files
        shell: bash
        run: |
          mkdir ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition
          cp -r scripts ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition/scripts
          cp ps/data.win ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition/data.win
          ls -laR ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition
      
      - name: Compress Windows Manual Version
        shell: bash
        run: 7z a -t7z -mx=9 ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer.7z ./${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer/

      - name: Compress Windows Manual Version PS
        shell: bash
        run: 7z a -t7z -mx=9 ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition.7z ./${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition/

      - name: Move Windows manual versions to Outputs
        shell: bash
        run: |
          cp ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer.7z Output/
          cp ${{ env.APPNAME }}_${{ env.APPVERSION }}_Windows-Manual-Installer_PS-Edition.7z Output/

      - name: Prepare Linux std files
        shell: bash
        run: |
          mkdir assets
          cp -r scripts assets/scripts
          cp data.win assets/game.unx
          ls -laR assets

      - name: Compress Linux std files
        uses: a7ul/tar-action@v1.2.0
        id: compress2
        with:
          command: c
          cwd: ./
          files: |
            ./assets/
            ./Lisez-Moi-PatchFR_Linux.txt
          outPath: Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Linux.tar.gz

      - name: Prepare Linux PS files
        shell: bash
        run: |
          rm assets/game.unx
          cp ps/data.win assets/game.unx
          ls -laR assets

      - name: Compress Linux ps files
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./assets/
            ./Lisez-Moi-PatchFR_Linux.txt
          outPath: Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Linux_PS-Edition.tar.gz

      - name: Prepare Vita std files
        shell: bash
        run: |
          mkdir -p Vita/rePatch/PCSB01166/games/
          cp -r scripts Vita/rePatch/PCSB01166/games/scripts
          mv Vita/rePatch/PCSB01166/games/scripts/eng Vita/rePatch/PCSB01166/games/scripts/en
          cp vita/game.win Vita/rePatch/PCSB01166/games/game.win
          ls -laR assets

      - name: Prepare Vita PS files
        shell: bash
        run: |
          mkdir -p Vita-PS/rePatch/PCSB01166/games/
          cp -r scripts Vita-PS/rePatch/PCSB01166/games/scripts
          mv Vita-PS/rePatch/PCSB01166/games/scripts/eng Vita-PS/rePatch/PCSB01166/games/scripts/en
          cp vita/ps/game.win Vita/rePatch/PCSB01166/games/game.win
          ls -laR assets
      
      - name: Compress Vita Version
        shell: bash
        run: 7z a -t7z -mx=9 Vita.7z ./Vita/

      - name: Compress Vita Version PS
        shell: bash
        run: 7z a -t7z -mx=9 Vita-PS.7z ./Vita-PS/

      - name: Move Vita versions to Outputs
        shell: bash
        run: |
          mv Vita.7z Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Vita.7z 
          mv Vita-PS.7z Output/${{ env.APPNAME }}_${{ env.APPVERSION }}_Vita_PS-Edition.7z 

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: D:\a\VA-11-Hall-A-French-Translation\VA-11-Hall-A-French-Translation\Output\*

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: release_notes.txt
          tag_name: ${{ env.APPVERSION }}
          make_latest: true
          files: Output/*